name: "Create PR"

on:
  workflow_dispatch: # 手動でトリガーして動作を確認するため
  schedule:
    # - cron: '0 0 * * 1-4' # UTC時間で月曜から木曜の午前0時に実行
    - cron: '0 23 * * *'


env:
  DEST_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          
          # 月初1日or月末の最終日の場合はブランチ作成を行わない
          CURRENT_DAY=$(date +'%d')
          LAST_DAY=$(date -d "$(date +%Y-%m-01) +1 month -1 day" +'%d')

          if [ "$CURRENT_DAY" -eq 1 ] || [ "$CURRENT_DAY" -eq "$LAST_DAY" ]; then
            echo "月初1日or月末の最終日なのでリリースブランチ作成をスキップします"
            exit 0
          fi

      - name: Generate release branch name
        run: |
          echo "RELEASE_BRANCH=release/${{ env.CURRENT_DATETIME }}_auto" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push a new branch
        run: |
          git switch -c ${{ env.RELEASE_BRANCH }}
          git commit --allow-empty -m "chore: Empty commit for PR creation"
          git push origin ${{ env.RELEASE_BRANCH }}

      - name: Create pull request using GitHub CLI
        run: |
          gh pr create \
            --title "${{ env.CURRENT_DATE }} 集約リリース" \
            --body "このブランチは、GitHub Actionsのワークフローで自動生成されました。" \
            --base ${{ env.DEST_BRANCH }} \
            --head ${{ env.RELEASE_BRANCH }}
          
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "GitHub Action Notification"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":bookmark_tabs: *Release Branch:* `${{ env.RELEASE_BRANCH }}`"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":link: *PR URL:* ${{ env.PR_URL }}"

